mysite/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path('', include('tienda.urls')),
    
    path('accounts/', include('django.contrib.auth.urls')), #usamos el login de django
    
]

from django.conf.urls import handler404
from django.conf.urls import handler500

handler404= "tienda.views.mi_error_404"
handler500= "tienda.views.mi_error_500"

tienda/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('',views.index,name='index'),
    path('clientes',views.lista_clientes,name='lista_clientes'),
    path('vendedores',views.lista_vendedores,name='lista_vendedores'),
    
    #registro de usuarios
    path('registrar',views.registrar_usuario,name='registrar_usuario'),
     
    #modelo de pieza  
    path('lista-catalogo',views.lista_catalogo,name='lista_catalogo'),
    path('crear-pieza',views.pieza_create,name='pieza_create'),
    path('pieza/<int:id_pieza>',views.dame_producto,name='dame_producto'),
    path('pieza-editar/<int:id_pieza>',views.pieza_editar,name='pieza_editar'),
    path('pieza-eliminar/<int:id_pieza>',views.pieza_eliminar,name='pieza_eliminar'),
    
    
    #modelo tienda
    path('tienda',views.lista_tienda,name='lista_tienda'),
    path('crear-tienda',views.tienda_create,name='tienda_create'),
    path('tienda/<int:id_tienda>',views.dame_tienda,name='dame_tienda'),
    path('tienda-eliminar/<int:id_tienda>',views.tienda_eliminar,name='tienda_eliminar'),
    path('tienda-editar/<int:id_tienda>',views.tienda_editar,name='tienda_editar'),
    
    
    #modelos cliente cuentaBancaria
    path('perfil-cliente/<int:id_usuario>',views.perfil_cliente,name='perfil_cliente'),
    path('detalle-cuentaBancaria-cliente/<int:id_usuario>',views.ver_detalle_cuentaBancaria_Cliente,name='ver_detalle_cuentaBancaria_Cliente'),
    path('crear-cuenta-bancaria', views.cuentaBancaria_create, name='cuentaBancaria_create'),   
    path('cuenta-bancaria-eliminar/<int:id_cuenta>',views.cuentaBancaria_delete,name='cuentaBancaria_delete'),
    path('cuenta-bancaria-editar/<int:id_cuentaaBancaria>',views.cuentaBancaria_editar,name='cuentaBancaria_editar'),
    
    #modelo vendedor datosVendedor
    path('perfil-vendedor/<int:id_usuario>',views.perfil_vendedor,name='perfil_vendedor'),
    path('detalle-vendedor/<int:id_usuario>',views.ver_detalle_datosVendedor,name='ver_detalle_datosVendedor'),
    path('agregar-datosVendedor', views.datosVendedor_create, name='datosVendedor_create'),
    path('datos-vendedor/<int:id_Datovendedor>',views.datosVendedor_delete,name='datosVendedor_delete'),
    path('datos-vendedor-editar/<int:id_Datovendedor>',views.datosVendedor_editar,name='datosVendedor_editar'),
    
    #tabla productosTienda many to many
    path('listas-productos-tienda', views.lista_ProductosTienda,name='lista_ProductosTienda'),
    path('add-producto-tienda', views.agregar_ProductoTienda,name='agregar_ProductoTienda'),
    path('eliminar-inventario/<int:id_productoTienda>',views.productoTienda_delete,name='productoTienda_delete'),
    path('editar-inventario/<int:id_ProductoTienda>', views.editar_ProductoTienda,name='editar_ProductoTienda'),


    #añadir pieza de una tienda en el carrito 
    path('anadir-pieza-carrito/<int:productoTienda_id>/', views.anadir_producto_tienda_carrito, name='anadir_producto_tienda_carrito'),


    #búsqueda pieza
    path('buscar-pieza', views.pieza_Buscar, name='pieza_Buscar'),
    path('busqueda-avanzada-pieza', views.busqueda_avanzada_pieza, name='busqueda_avanzada_pieza'),
    
    #tabla pedidos
    path('pedidos',views.lista_pedidos,name='lista_pedidos'),
    # path('crear-pedido',views.pedido_create,name='pedido_create'),
    
    #linea de pedido
    path('detalle-linea-pedido/<int:id_pedido>',views.dame_lineaPedido,name='dame_lineaPedido'),
    path('listar-linea-pedido-carrito/<int:id_usuario>',views.listarLineaPedidoCarrito,name='listarLineaPedidoCarrito'),
    path('eliminar-linea-pedido/<int:id_lineaPedido>',views.lineaPedido_delete,name='lineaPedido_delete'),
    path('editar-linea-pedido/<int:id_lineaPedido>/', views.editar_linea_pedido, name='editar_linea_pedido'),
    
    # urls.py
    path('finalizar-pedido/<int:pedido_id>/', views.finalizar_pedido, name='finalizar_pedido'),
    
    #devolucion
    path('devolucion/<int:lineaPedido_id>/', views.devolver_pieza, name='devolver_pieza'),
    path('lista-devoluciones', views.lista_devoluciones, name='lista_devoluciones'),
    path('devolucion/aceptar/<int:id_devolucion>/', views.aceptar_devolucion, name='aceptar_devolucion'),
    path('devolucion/denegar/<int:id_devolucion>/', views.denegar_devolucion, name='denegar_devolucion'),

    #datos de la api
    path('lista-productos-terceros/', views.listar_productos_terceros_api, name='listar_productos_terceros_api'),
    path('crear-producto-tercero/', views.crear_producto_tercero, name='crear_producto_tercero'),
    path('editar-nombre-producto-tercero/<int:producto_id>', views.editar_nombre_producto_tercero, name='editar_nombre_producto_tercero'),
    path('eliminar-producto/<int:producto_id>/', views.eliminar_producto, name='eliminar_producto'),
        

    
]

tienda/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class Usuario(AbstractUser):
    ADMINISTRADOR = 1
    CLIENTE = 2
    VENDEDOR = 3
    ROLES = (
        (ADMINISTRADOR, 'administrador'),
        (CLIENTE, 'cliente'),
        (VENDEDOR, 'vendedor'),
    )
    
    rol  = models.PositiveSmallIntegerField(
        choices=ROLES,default=2
    )



class Vendedor(models.Model):
    
    usuario = models.OneToOneField(Usuario, on_delete= models.CASCADE)
    
    def __str__(self):
        return self.usuario.username
    
    
class Pieza(models.Model):
    nombre= models.CharField(max_length=100)
    version= models.CharField(max_length=100)
    referencia= models.CharField(max_length=100)
    ESTADO = [("N", "Nueva"), ("R", "Recuperada"), ("REC", "Reconstruida")]
    estado = models.CharField(max_length=3, choices=ESTADO)
    descripcion= models.TextField()
    marca= models.CharField(max_length=100)
    precio= models.FloatField(default=1.0) 
    anio= models.IntegerField()
    
    def __str__(self):
        return self.nombre


class Cliente(models.Model):
    usuario = models.OneToOneField(Usuario, on_delete=models.CASCADE)
    
    #se pone en decimal para que se pueda relejar la devolución del precio de la pieza
    puntos = models.FloatField(default=0.0)  # Puntos del cliente al momento de la devolución
    
    
    def __str__(self):
        return self.usuario.username
    
    
    
class Tienda(models.Model):
    direccion = models.CharField(max_length=100)
    telefono = models.CharField(max_length=15)
    email= models.EmailField()
    vendedor= models.ForeignKey(Vendedor, on_delete= models.CASCADE, default=None, null=True)
    piezas= models.ManyToManyField(Pieza, through='Producto_Tienda',related_name="tienda_Inventarios")
    
    def __str__(self):
        return self.direccion


class CuentaBancaria(models.Model):
    iban = models.CharField(max_length=25)
    banco = models.CharField(max_length=25)
    MONEDA= [("EUR", "Euro"), ("DOL", "Dolar"), ("LIB", "Libra")]
    moneda = models.CharField(max_length=3, choices=MONEDA, default="E")
    cliente= models.OneToOneField(Cliente, on_delete=models.CASCADE)
    
    
    def __str__(self):
        return self.banco

class DatosVendedor(models.Model):
    direccion = models.CharField(max_length=100)
    facturacion = models.CharField(max_length=100)
    vendedor= models.OneToOneField(Vendedor, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.direccion
    
    
#anteriormente inventario
class Producto_Tienda(models.Model):
    tienda= models.ForeignKey(Tienda, on_delete= models.CASCADE)
    pieza= models.ForeignKey(Pieza, on_delete= models.CASCADE)
    stock= models.IntegerField() 
    precio= models.FloatField(default=1.0) 
    

    
class Pedido(models.Model):
    ESTADO = [
        ("P", "Pendiente"),
        ("C", "Completado"),
        ("A", "Anulado")
    ]
    estado = models.CharField(max_length=1, choices=ESTADO, default="P")
    fecha = models.DateTimeField(auto_now_add=True) #asigna la fecha y hora actual al crear el pedido
    direccion = models.CharField(max_length=100)

    
    # Relación muchos a muchos utilizando la tabla Pedido como intermedia
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE, related_name='pedidos')
    
    #Relación many to one 
    tienda= models.ForeignKey(Tienda, on_delete= models.CASCADE)


    
    def __str__(self):
        return f"Pedido de {self.cliente.usuario.username}"
    
    
class LineaPedido(models.Model):
    pedido= models.ForeignKey(Pedido, on_delete= models.CASCADE, related_name="pedido_lineaPedido")
    pieza= models.ForeignKey(Pieza, on_delete= models.CASCADE, related_name="pieza_lineaPedido") 
    tienda= models.ForeignKey(Tienda, on_delete= models.CASCADE, related_name="tienda_lineaPedido")
    precio= models.FloatField(default=1.0) 
    cantidad= models.IntegerField() 



class Pago(models.Model):
    #Un pago está asociado a un solo pedido, y un pedido solo puede tener un pago
    pedido = models.OneToOneField(Pedido, on_delete=models.CASCADE, related_name="pago")
    
    #El pago se hace desde una cuenta bancaria, así que conectamos con CuentaBancaria usando ForeignKey
    cuenta_bancaria = models.ForeignKey(CuentaBancaria, on_delete=models.CASCADE, related_name="pagos")
    monto = models.FloatField()
    fecha_pago = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Pago de {self.monto} € por {self.pedido}"
    
class Devolucion(models.Model):
    #puedo tener muchas devuluciones que apuntan a una misma linea pedido (one to many)
    lineaPedido = models.OneToOneField(LineaPedido, on_delete=models.CASCADE, related_name="devoluciones")
    
    #cliente puede tener muchas devoluciones (one to many)
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE, related_name="devoluciones")
    fecha_devolucion = models.DateTimeField(auto_now_add=True)
    ESTADO = [
        ("P", "Pendiente"),
        ("R", "Resuelta"),
        ("D", "Denegada"),
    ]
    estado = models.CharField(max_length=1, choices=ESTADO, default="P")
    


    def __str__(self):
        return f"Devolución del pedido {self.pedido.id} - Motivo: {self.estado}"

    


    
    


    
    
    

tienda/templates/lineaPedido/carrito.html
{% extends "estructura/principal.html" %}

{% block contenido %}
<div class="container my-5">
  <h2 class="mb-4">Carrito</h2>

  {% for item in carrito %}
  <div class="card mb-3">
    <div class="row g-0">
      <div class="col-md-2 d-flex align-items-center justify-content-center">
        <img src="" class="img-fluid rounded-start" alt="Imagen del producto" style="max-height: 150px;">
      </div>
      <div class="col-md-10">
        <div class="card-body">
          <h5 class="card-title">{{ item.pieza.nombre }}</h5>
          <p class="card-text text-muted">
            {{ item.pieza.descripcion|truncatechars:150 }}
          </p>
          <div class="mb-2">
            <span class="fw-bold">Precio: </span>{{ item.pieza.precio }}€
          </div>

          <div class="d-flex align-items-center mb-3">
            <form method="POST" action="" class="d-flex align-items-center">
              {% csrf_token %}
              <button class="btn btn-outline-secondary btn-sm me-2" name="action" value="restar">−</button>
              <span class="px-2">{{ item.cantidad }}</span>
              <button class="btn btn-outline-secondary btn-sm me-3" name="action" value="sumar">+</button>
            </form>

            <form method="POST" action="">
              {% csrf_token %}
              <button class="btn btn-danger btn-sm me-2">Eliminar</button>
            </form>

            <a href="#" class="btn btn-outline-primary btn-sm me-2">Guardar para más tarde</a>
            <a href="#" class="btn btn-outline-secondary btn-sm">Compartir</a>
          </div>

          {% if item.es_regalo %}
            <span class="badge bg-success">Es un regalo 🎁</span>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
  {% endfor %}

  <!-- Subtotal -->
  <div class="text-end">
    <h5 class="fw-bold">Subtotal ({{ total_productos }} productos): US${{ total_precio }}</h5>
  </div>
</div>
{% endblock %}

tienda/templates/lineaPedido/lineaPedido_detalle.html
{% extends "estructura/principal.html" %}
{% block contenido %}
<div class="container my-5">
    <h1 class="mb-4">Detalles del pedido</h1>

    <!-- Sección de cuenta bancaria -->
    {% if cuenta_bancaria %}
    <div class="card mb-5 shadow">
        <div class="card-header bg-primary text-white">
            <h4>Datos de la cuenta bancaria del cliente</h4>
        </div>
        <div class="card-body">
            <p><strong>Banco:</strong> {{ cuenta_bancaria.banco }}</p>
            <p><strong>IBAN:</strong> {{ cuenta_bancaria.iban }}</p>
            <p><strong>Moneda:</strong> {{ cuenta_bancaria.get_moneda_display }}</p>
        </div>
    </div>
    {% else %}
    <div class="alert alert-warning">
        Este cliente no tiene una cuenta bancaria registrada.
    </div>
    {% endif %}


    <!-- Sección de líneas de pedido -->
    <h2 class="mb-3">Líneas de pedido</h2>

    {% for registro in pieza_devoluciones%}
    <div class="card h-100 shadow-sm mb-4">
        <div class="card-body">
            <h5 class="card-title">{{ registro.linea_pedido.pieza.nombre }}</h5>
            <p><strong>Descripción:</strong> {{ registro.linea_pedido.pieza.descripcion }}</p>
            <p><strong>Versión:</strong> {{ registro.linea_pedido.pieza.version }}</p>
            <p><strong>Referencia:</strong> {{ registro.linea_pedido.pieza.referencia }}</p>
            <p><strong>Tienda:</strong> {{ registro.linea_pedido.tienda.direccion }}</p>
            <p><strong>Precio unitario:</strong> {{ registro.linea_pedido.precio }} €</p>
            <p><strong>Cantidad:</strong> {{ registro.linea_pedido.cantidad }}</p>
        
            <!-- Mostrar el estado de la devolución -->
            {% if registro.devuelto %}
            <p><strong>Devolución solicitada</strong></p>
            {% else %}
            <!-- Botón de devolución -->
            <form method="post" action="{% url 'devolver_pieza' registro.linea_pedido.id %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger mt-2">
                    <i class="fas fa-undo"></i> Devolver
                </button>
            </form>
            
            {% endif %}
        
        </div>
    </div>
    {% empty %}
    <div class="alert alert-info" role="alert">
        No hay líneas de pedido registradas.
    </div>
    {% endfor %}

    <!-- Total general -->
    {% if total %}
    <div class="card mt-4 shadow">
        <div class="card-body">
            <h4 class="card-title text-end"><strong>Total del pedido:</strong> {{ total }} €</h4>
        </div>
    </div>
    {% endif %}

</div>

{% endblock %}

tienda/templates/lineaPedido/totalPiezascarrito.html
{% extends "estructura/principal.html" %}

{% block contenido %}
<div class="container my-5">
  <h2 class="mb-4">Pedido actual</h2>

  {% for item in carrito %}
  <div class="card mb-3">
    <div class="row g-0">
      <div class="col-md-2 d-flex align-items-center justify-content-center">
        <img src="" class="img-fluid rounded-start" alt="Imagen del producto" style="max-height: 150px;">
      </div>
      <div class="col-md-10">
        <div class="card-body">
          <h5 class="card-title">{{ item.pieza.nombre }}</h5>
          <p class="card-text text-muted">
            {{ item.pieza.descripcion|truncatechars:150 }}
          </p>
          <div class="mb-2">
            <span class="fw-bold">Precio: </span>{{ item.precio }}€
          </div>

          <div class="mb-2">
            <span class="fw-bold">Cantidad: </span>{{ item.cantidad }}
          </div>

          <div class="d-flex align-items-center mb-3">
            <!-- Botón Editar -->
            <a href="{% url 'editar_linea_pedido' item.id %}" class="btn btn-primary btn-sm me-2">Editar</a>

            <!-- Botón Eliminar -->
            <form method="POST" action="{% url 'lineaPedido_delete' item.id %}" onsubmit="return eliminar();">
              {% csrf_token %}
              <button class="btn btn-danger btn-sm">Eliminar</button>
            </form>
          </div>

        </div>
      </div>
    </div>
  </div>
  {% endfor %}

  <!-- Subtotal -->
  <div class="text-end">
    <h5 class="fw-bold"> Total de piezas: {{ total_productos }}</h5>
    <h5 class="fw-bold"> Precio total: {{ total_precio }}€</h5>
  </div>

  <!-- Botón Finalizar Pedido -->
  <div class="text-end mt-4">
    {% if pedido %}
    <form method="GET" action="{% url 'finalizar_pedido' pedido.id %}">
      <button type="submit" class="btn btn-success btn-lg">Tramitar pedido</button>
    </form>
    {% endif %}

  </div>
</div>




{% endblock %}